# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :build do
    build_app
  end

  lane :run_ios_tests do
    scan(
      scheme: "orderMe",
      devices: ["iPhone 6s", "iPhone X"])

     # gym(scheme: "orderMe", 
     # xcargs: "-allowProvisioningUpdates",
     # skip_package_ipa: true) # export_method: 'app-store')
  end	

end

